// The shop's rail. 25 garments (20 men, 5 women), 5 colourways each, one
// photograph per garment — not one per colourway.
//
// THE MONEY DECISION: we photograph 25 images, not 125. The
// colourway is applied as a sentence in the try-on prompt at generation
// time ("recoloured to deep wine #6E2639"), which costs nothing and yields
// 125 combinations from 25 files. Do not add a second image per colourway.

export const CATEGORIES = {
  MEN: "men",
  WOMEN: "women",
};

export const GARMENTS = [
  // ---------------- menswear (20) ----------------
  {
    id: "zardozi-bandhgala-set",
    name: "Zardozi Bandhgala Set",
    gender: "men",
    category: "bandhgala",
    fabric: "Maroon silk bandhgala with zardozi, ivory churidar",
    price: 38500,
    image: "/catalogue/zardozi-bandhgala-set.jpg",
    colourways: [
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "navy-double-breasted-blazer",
    name: "Double-Breasted Blazer",
    gender: "men",
    category: "blazer",
    fabric: "Navy wool blazer with brass buttons, white trousers",
    price: 21500,
    image: "/catalogue/navy-double-breasted-blazer.jpg",
    colourways: [
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Deep Wine", hex: "#6E2639" },
    ],
  },
  {
    id: "burgundy-brocade-bomber",
    name: "Brocade Bomber & Joggers",
    gender: "men",
    category: "bomber",
    fabric: "Burgundy jacquard bomber over black joggers",
    price: 14800,
    image: "/catalogue/burgundy-brocade-bomber.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Champagne Gold", hex: "#C9A961" },
    ],
  },
  {
    id: "black-peak-lapel-tuxedo",
    name: "Peak-Lapel Tuxedo",
    gender: "men",
    category: "tuxedo",
    fabric: "Black wool tuxedo with satin lapels",
    price: 46000,
    image: "/catalogue/black-peak-lapel-tuxedo.jpg",
    colourways: [
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
    ],
  },
  {
    id: "mint-linen-shirt-shorts",
    name: "Linen Shirt & Shorts",
    gender: "men",
    category: "linen-set",
    fabric: "Pure linen camp shirt with stone shorts",
    price: 5400,
    image: "/catalogue/mint-linen-shirt-shorts.jpg",
    colourways: [
      { name: "Seafoam Mint", hex: "#9FD8C0" },
      { name: "Sky Blue", hex: "#A9C6E8" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Dusty Rose", hex: "#B8778A" },
    ],
  },
  {
    id: "emerald-velvet-waistcoat",
    name: "Velvet Nehru Waistcoat",
    gender: "men",
    category: "nehru-jacket",
    fabric: "Emerald velvet waistcoat, white kurta and trousers",
    price: 16500,
    image: "/catalogue/emerald-velvet-waistcoat.jpg",
    colourways: [
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "black-leather-biker-set",
    name: "Leather Biker Set",
    gender: "men",
    category: "leather-jacket",
    fabric: "Quilted leather biker jacket with coated denim",
    price: 32000,
    image: "/catalogue/black-leather-biker-set.jpg",
    colourways: [
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Camel Tan", hex: "#B08655" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Midnight Navy", hex: "#1B2438" },
    ],
  },
  {
    id: "gold-paisley-sherwani",
    name: "Paisley Sherwani",
    gender: "men",
    category: "sherwani",
    fabric: "Navy silk sherwani with gold paisley zari",
    price: 62000,
    image: "/catalogue/gold-paisley-sherwani.jpg",
    colourways: [
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "buffalo-check-workwear",
    name: "Buffalo Check Workwear",
    gender: "men",
    category: "workwear",
    fabric: "Flannel buffalo-check shirt, tee and carpenter pants",
    price: 7800,
    image: "/catalogue/buffalo-check-workwear.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Rust Copper", hex: "#A6512C" },
    ],
  },
  {
    id: "sage-cardigan-layer",
    name: "Waffle Cardigan Layer",
    gender: "men",
    category: "knitwear",
    fabric: "Sage waffle-knit cardigan, oxford shirt, flannel trousers",
    price: 9200,
    image: "/catalogue/sage-cardigan-layer.jpg",
    colourways: [
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Camel Tan", hex: "#B08655" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
    ],
  },
  {
    id: "suede-trucker-jacket",
    name: "Suede Trucker Jacket",
    gender: "men",
    category: "trucker-jacket",
    fabric: "Tan suede trucker jacket with raw denim",
    price: 24500,
    image: "/catalogue/suede-trucker-jacket.jpg",
    colourways: [
      { name: "Camel Tan", hex: "#B08655" },
      { name: "Rust Copper", hex: "#A6512C" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Midnight Navy", hex: "#1B2438" },
    ],
  },
  {
    id: "navy-peacoat-denim",
    name: "Peacoat & Denim Shirt",
    gender: "men",
    category: "coat",
    fabric: "Navy wool peacoat over chambray, green cords",
    price: 19800,
    image: "/catalogue/navy-peacoat-denim.jpg",
    colourways: [
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Camel Tan", hex: "#B08655" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "mustard-hoodie-denim",
    name: "Hoodie & Distressed Denim",
    gender: "men",
    category: "streetwear",
    fabric: "Mustard fleece hoodie with light-wash jeans",
    price: 4600,
    image: "/catalogue/mustard-hoodie-denim.jpg",
    colourways: [
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Sky Blue", hex: "#A9C6E8" },
    ],
  },
  {
    id: "oxford-shirt-chinos",
    name: "Oxford Shirt & Chinos",
    gender: "men",
    category: "smart-casual",
    fabric: "Blue oxford button-down with charcoal chinos",
    price: 4200,
    image: "/catalogue/oxford-shirt-chinos.jpg",
    colourways: [
      { name: "Sky Blue", hex: "#A9C6E8" },
      { name: "Optic White", hex: "#F7F7F4" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Dusty Rose", hex: "#B8778A" },
      { name: "Sage Olive", hex: "#5C6E4F" },
    ],
  },
  {
    id: "white-polo-selvedge",
    name: "Polo & Selvedge Denim",
    gender: "men",
    category: "polo",
    fabric: "Tipped piqué polo with indigo selvedge jeans",
    price: 3800,
    image: "/catalogue/white-polo-selvedge.jpg",
    colourways: [
      { name: "Optic White", hex: "#F7F7F4" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Bottle Green", hex: "#1F4235" },
      { name: "Deep Wine", hex: "#6E2639" },
    ],
  },
  {
    id: "puffer-vest-joggers",
    name: "Puffer Vest & Joggers",
    gender: "men",
    category: "athleisure",
    fabric: "Quilted puffer vest, henley and fleece joggers",
    price: 8900,
    image: "/catalogue/puffer-vest-joggers.jpg",
    colourways: [
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Rust Copper", hex: "#A6512C" },
    ],
  },
  {
    id: "techwear-cargo-set",
    name: "Techwear Shell & Cargos",
    gender: "men",
    category: "techwear",
    fabric: "Hooded technical shell with olive cargo joggers",
    price: 12400,
    image: "/catalogue/techwear-cargo-set.jpg",
    colourways: [
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Charcoal Grey", hex: "#2B2E33" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Rust Copper", hex: "#A6512C" },
    ],
  },
  {
    id: "navy-turtleneck-check",
    name: "Turtleneck & Check Trousers",
    gender: "men",
    category: "turtleneck",
    fabric: "Merino turtleneck with Glen-check trousers",
    price: 8600,
    image: "/catalogue/navy-turtleneck-check.jpg",
    colourways: [
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Onyx Black", hex: "#17181B" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Camel Tan", hex: "#B08655" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
    ],
  },
  {
    id: "white-bandhgala-shirt-olive",
    name: "Mandarin Shirt & Olive Trousers",
    gender: "men",
    category: "mandarin-set",
    fabric: "White band-collar linen shirt, olive linen trousers",
    price: 5200,
    image: "/catalogue/white-bandhgala-shirt-olive.jpg",
    colourways: [
      { name: "Optic White", hex: "#F7F7F4" },
      { name: "Sky Blue", hex: "#A9C6E8" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Seafoam Mint", hex: "#9FD8C0" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
    ],
  },
  {
    id: "cream-aran-cord",
    name: "Aran Knit & Corduroy",
    gender: "men",
    category: "aran-knit",
    fabric: "Cream cable-knit jumper with brown cords",
    price: 7400,
    image: "/catalogue/cream-aran-cord.jpg",
    colourways: [
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Camel Tan", hex: "#B08655" },
    ],
  },

  // ---------------- womenswear (5) ----------------
  {
    id: "banarasi-silk-saree",
    name: "Banarasi Silk Saree",
    gender: "women",
    category: "saree",
    fabric: "Pure Banarasi silk with zari border",
    price: 32000,
    image: "/catalogue/banarasi-silk-saree.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Peacock Blue", hex: "#0F5C6B" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Bottle Green", hex: "#1F4235" },
    ],
  },
  {
    id: "floor-length-anarkali",
    name: "Floor-Length Anarkali",
    gender: "women",
    category: "anarkali",
    fabric: "Georgette Anarkali with gota embroidery",
    price: 18500,
    image: "/catalogue/floor-length-anarkali.jpg",
    colourways: [
      { name: "Dusty Rose", hex: "#B8778A" },
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Deep Teal", hex: "#164B47" },
      { name: "Blush Pink", hex: "#D9AFAE" },
      { name: "Royal Purple", hex: "#4A2545" },
    ],
  },
  {
    id: "zardozi-lehenga-choli",
    name: "Zardozi Lehenga Choli",
    gender: "women",
    category: "lehenga-choli",
    fabric: "Zardozi-embroidered raw silk lehenga choli",
    price: 68000,
    image: "/catalogue/zardozi-lehenga-choli.jpg",
    colourways: [
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Midnight Navy", hex: "#1B2438" },
      { name: "Champagne Gold", hex: "#C9A961" },
      { name: "Maroon", hex: "#5A1B24" },
      { name: "Onyx Black", hex: "#17181B" },
    ],
  },
  {
    id: "chanderi-salwar-kameez",
    name: "Chanderi Salwar Kameez",
    gender: "women",
    category: "salwar-kameez",
    fabric: "Chanderi silk-cotton salwar kameez",
    price: 7200,
    image: "/catalogue/chanderi-salwar-kameez.jpg",
    colourways: [
      { name: "Pearl Grey", hex: "#C7C2B8" },
      { name: "Sage Olive", hex: "#5C6E4F" },
      { name: "Blush Pink", hex: "#D9AFAE" },
      { name: "Ivory Cream", hex: "#F1E9DA" },
      { name: "Dusty Rose", hex: "#B8778A" },
    ],
  },
  {
    id: "mustard-sharara-set",
    name: "Mirror-Work Sharara Set",
    gender: "women",
    category: "sharara-set",
    fabric: "Mirror-embroidered silk sharara with dupatta",
    price: 14500,
    image: "/catalogue/mustard-sharara-set.jpg",
    colourways: [
      { name: "Mustard", hex: "#C79A3A" },
      { name: "Deep Wine", hex: "#6E2639" },
      { name: "Peacock Blue", hex: "#0F5C6B" },
      { name: "Royal Purple", hex: "#4A2545" },
      { name: "Champagne Gold", hex: "#C9A961" },
    ],
  },
];

export const byId = (id) => GARMENTS.find((g) => g.id === id);

export const inr = (n) => "₹" + n.toLocaleString("en-IN");
